version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true # Necesario para file watching en Docker

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000" # API
      - "9229:9229" # Debugger
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - DB_HOST=mysql
      - DB_USER=devuser
      - DB_PASSWORD=devpass
      - DB_NAME=devdb
      - NODE_ENV=development
      - DEBUG=express:* # Logs detallados de Express
    command: npm run dev

  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_DATABASE=devdb
      - MYSQL_USER=devuser
      - MYSQL_PASSWORD=devpass
    ports:
      - "3306:3306" # Opcional, solo si necesitas acceso directo
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql # SQL inicial (opcional)

volumes:
  mysql_data: